<?php
/**
 * @var $block \Lofmp\FacebookLiveChat\Block\FacebookChat
 */
?>
<?php
$facebooklive = $block->getFacebookInfo();
if ($facebooklive && $facebooklive->getStatus() && $facebooklive->getPageId()) :
    $helper = $this->helper("Lofmp\FacebookLiveChat\Helper\Data");
    $themeColor = $facebooklive->getThemeColor();
    $themeColor = $themeColor ? $block->escapeUrl($themeColor) : "#44bec7";
    $loggedInGreeting = $facebooklive->getLoggedInGreeting();
    $loggedInGreeting = $loggedInGreeting ? $loggedInGreeting : __("Hello! Welcome to our shop");
    $loggedOutGreeting = $facebooklive->getLoggedOutGreeting();
    $loggedOutGreeting = $loggedOutGreeting ? $loggedOutGreeting : __("Hello! Welcome to our shop");
    $languageCode = $helper->getCurrentLocaleCode();
    $languageCode = $languageCode ? trim($languageCode): "en_US";
?>
<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<!-- Your Plugin chat code -->
<div id="fb-customer-chat" class="fb-customerchat">
</div>
<script>
    var chatbox = document.getElementById('fb-customer-chat');
    chatbox.setAttribute("page_id", "<?= $block->escapeUrl($facebooklive->getPageId()); ?>");
    chatbox.setAttribute("attribution", "biz_inbox");
    chatbox.setAttribute("logged_in_greeting", "<?= $block->escapeHtmlAttr($loggedInGreeting); ?>");
    chatbox.setAttribute("logged_out_greeting", "<?= $block->escapeHtmlAttr($loggedOutGreeting); ?>");
    chatbox.setAttribute("theme_color", "<?= $themeColor; ?>");

    window.fbAsyncInit = function() {
        FB.init({
        xfbml            : true,
        version          : 'v12.0'
        });
    };

    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/<?= $block->escapeHtmlAttr($languageCode); ?>/sdk/xfbml.customerchat.js';
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<?php endif; ?>
